#!/bin/bash

# Usage zilla -create-systemd\-enter-systemd container-name

# Requires debootstrap

#Note this is a security risk, but going to assume your systemd container is secure
#Main purpose of zilla is to run other Linux varients or contain dependencies on top of your distro of choice not to serve as a secure container
export SYSTEMD_SECCOMP=0

CHROOT_LOCATION=/mnt/md0/chroots
DIST_DATA_LOCATION=/mnt/md0/custom-software/dist-data
UBUNTU_VERSION=focal

case $1 in
        -create)
                /usr/bin/debootstrap --components=main,universe,multiverse,restricted --include=systemd-container,dbus $UBUNTU_VERSION $CHROOT_LOCATION/$2 http://archive.ubuntu.com/ubuntu/
                /usr/bin/cp $DIST_DATA_LOCATION/ubuntu/.bashrc $CHROOT_LOCATION/$2/root/.bashrc
                ln -s $CHROOT_LOCATION/$2 /var/lib/machines/$2
                mkdir /etc/systemd/nspawn 2>/dev/null
                cp $DIST_DATA_LOCATION/ubuntu/container.nspawn /etc/systemd/nspawn/$2.nspawn
                zilla -enter-systemd $2 init
                ;;
        -enter)
                cd $CHROOT_LOCATION/
                /usr/bin/touch ./$2/root/$3
                systemd-nspawn -D ./$2 --machine=$2 --bind=/dev/nvidia0
                sleep 10
                rm ./$2/root/$3
                ;;
        *)
                echo "-create-systemd <name>, -enter-systemd <name> <tmp file>"
                ;;
esac