#!/bin/bash

# Usage (temp_file is used so you can execute different commands automatically when entering chroot)
# To create: zilla -create disto name
# To enter most chroots: zilla -enter name temp_file
# To enter chroots with special edge cases (ex Alpine): zilla -enter name temp_file distro

#Note this is a security risk, but going to assume your systemd container is secure
#Main purpose of zilla is to run other Linux varients or contain dependencies on top of your distro of choice not to serve as a secure container
export SYSTEMD_SECCOMP=0

case $1 in
        -create)
                case $2 in
                        ubuntu)
                                /usr/bin/debootstrap --variant=buildd focal /mnt/chroot/$3 http://archive.ubuntu.com/ubuntu/
                                /usr/bin/cp /mnt/dist-data/ubuntu/sources.list /mnt/chroot/$3/etc/apt/sources.list
                                /usr/bin/cp /mnt/dist-data/ubuntu/.bashrc /mnt/chroot/$3/root/.bashrc
                                ;;
                        alpine)
                                cd /mnt/chroot/
                                sudo alpine-chroot-install -d /mnt/chroot/$3 -p build-base -p cmake
                                ;;
                        arch)
                                CHROOT=/mnt/chroot/$3
                                /usr/bin/mkchroot $CHROOT base-devel
                                /usr/bin/rm $3.lock
                                /usr/bin/cp /mnt/dist-data/arch/.bashrc /mnt/chroot/$3/root/.bashrc
                                /usr/bin/cp /mnt/dist-data/arch/pacman.conf /mnt/chroot/$3/etc/pacman.conf
                                /usr/bin/cp /mnt/dist-data/arch/sudoers /mnt/chroot/$3/etc/sudoers
                                /usr/bin/cp /mnt/dist-data/arch/.bash_profile /mnt/chroot/$3/root/.bash_profile
                                cd /mnt/chroot/$3/usr/local/bin
                                /usr/bin/wget https://raw.githubusercontent.com/FriedMicro/frost/main/frost
                                /usr/bin/chmod +x frost
                                ;;
                esac
                ;;
        -enter)
                case $4 in
                        alpine)
                                /mnt/chroot/$2/enter-chroot
                                ;;
                        *)
                                cd /mnt/chroot/$2
                                /usr/bin/touch ./root/$3
                                /usr/bin/groot
                                /usr/bin/rm ./root/$3
                                ;;
                esac
                ;;
        -create-systemd)
		/usr/bin/debootstrap --include=systemd-container focal /mnt/chroot/$2 http://archive.ubuntu.com/ubuntu/
                /usr/bin/cp /mnt/dist-data/ubuntu/sources.list /mnt/chroot/$2/etc/apt/sources.list
                /usr/bin/cp /mnt/dist-data/ubuntu/.bashrc /mnt/chroot/$2/root/.bashrc
                ln -s /mnt/chroot/$2 /var/lib/machines/$2
                cp /mnt/dist-data/ubuntu/container.nspawn /etc/systemd/nspawn/$2.nspawn
                systemd-nspawn -D ./$2
		;;
        -enter-systemd)
                cd /mnt/chroot/
                /usr/bin/touch ./$2/root/$3
                systemd-nspawn --machine=$2 -b -D ./$2 &
                sleep 10
                sudo machinectl shell root@$2
                rm ./$2/root/$3
                ;;
        *)
                echo "-create <base> <name>, -enter <chroot name> <tmp file>, -create-systemd <name>, -enter-systemd <name> <tmp file>"
		;;
esac
